-- ============================================
-- ZRL项目协同管理系统 - 初始化数据脚本
-- 作者：系统管理员
-- 创建时间：2024年1月
-- 说明：为三张核心表插入测试数据
-- ============================================

-- 1. 插入分组数据（如果不存在）
INSERT INTO ZRLDATABASE."GROUPS" (NAME)
SELECT '开发组' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ZRLDATABASE."GROUPS" WHERE NAME = '开发组')
UNION ALL
SELECT '测试组' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ZRLDATABASE."GROUPS" WHERE NAME = '测试组')
UNION ALL
SELECT '设计组' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ZRLDATABASE."GROUPS" WHERE NAME = '设计组')
UNION ALL
SELECT '项目管理组' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ZRLDATABASE."GROUPS" WHERE NAME = '项目管理组')
UNION ALL
SELECT '运维组' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ZRLDATABASE."GROUPS" WHERE NAME = '运维组')
UNION ALL
SELECT '数据分析组' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ZRLDATABASE."GROUPS" WHERE NAME = '数据分析组')
UNION ALL
SELECT '产品组' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ZRLDATABASE."GROUPS" WHERE NAME = '产品组')
UNION ALL
SELECT '质量保证组' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ZRLDATABASE."GROUPS" WHERE NAME = '质量保证组');

-- 显示插入的分组数量
SELECT '已插入分组数: ' || COUNT(*) || ' 条' FROM ZRLDATABASE."GROUPS";

-- 2. 插入项目数据（如果不存在）
INSERT INTO ZRLDATABASE.PROJECTS (NAME, DESCRIPTION, STATUS)
SELECT 'ZRL数字化平台', '中石化ZRL项目数字化管理平台建设', 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ZRLDATABASE.PROJECTS WHERE NAME = 'ZRL数字化平台')
UNION ALL
SELECT 'ERP系统升级', '企业资源计划系统升级项目', 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ZRLDATABASE.PROJECTS WHERE NAME = 'ERP系统升级')
UNION ALL
SELECT '安全防护体系', '网络安全防护体系建设', 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ZRLDATABASE.PROJECTS WHERE NAME = '安全防护体系')
UNION ALL
SELECT '移动办公平台', '企业移动办公应用开发', 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ZRLDATABASE.PROJECTS WHERE NAME = '移动办公平台')
UNION ALL
SELECT '数据仓库建设', '企业级数据仓库系统', 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ZRLDATABASE.PROJECTS WHERE NAME = '数据仓库建设');

-- 显示插入的项目数量
SELECT '已插入项目数: ' || COUNT(*) || ' 条' FROM ZRLDATABASE.PROJECTS;

-- 3. 插入项目成员数据（如果不存在）
-- 注意：这里使用MERGE语句或INSERT...SELECT避免重复插入

-- 为ZRL数字化平台项目添加成员
INSERT INTO ZRLDATABASE.PROJECT_MEMBERS (PROJECT_ID, GROUP_ID, MEMBER_NAME, POSITION, MEMBER_STATUS)
SELECT 
    p.ID AS PROJECT_ID,
    g.ID AS GROUP_ID,
    '张三' AS MEMBER_NAME,
    '项目经理' AS POSITION,
    1 AS MEMBER_STATUS
FROM ZRLDATABASE.PROJECTS p, ZRLDATABASE."GROUPS" g
WHERE p.NAME = 'ZRL数字化平台' AND g.NAME = '项目管理组'
AND NOT EXISTS (
    SELECT 1 FROM ZRLDATABASE.PROJECT_MEMBERS pm 
    WHERE pm.MEMBER_NAME = '张三' AND pm.PROJECT_ID = p.ID
);

INSERT INTO ZRLDATABASE.PROJECT_MEMBERS (PROJECT_ID, GROUP_ID, MEMBER_NAME, POSITION, MEMBER_STATUS)
SELECT 
    p.ID AS PROJECT_ID,
    g.ID AS GROUP_ID,
    '李四' AS MEMBER_NAME,
    '后端开发工程师' AS POSITION,
    2 AS MEMBER_STATUS
FROM ZRLDATABASE.PROJECTS p, ZRLDATABASE."GROUPS" g
WHERE p.NAME = 'ZRL数字化平台' AND g.NAME = '开发组'
AND NOT EXISTS (
    SELECT 1 FROM ZRLDATABASE.PROJECT_MEMBERS pm 
    WHERE pm.MEMBER_NAME = '李四' AND pm.PROJECT_ID = p.ID
);

-- 为ERP系统升级项目添加成员
INSERT INTO ZRLDATABASE.PROJECT_MEMBERS (PROJECT_ID, GROUP_ID, MEMBER_NAME, POSITION, MEMBER_STATUS)
SELECT 
    p.ID AS PROJECT_ID,
    g.ID AS GROUP_ID,
    '王五' AS MEMBER_NAME,
    '测试工程师' AS POSITION,
    2 AS MEMBER_STATUS
FROM ZRLDATABASE.PROJECTS p, ZRLDATABASE."GROUPS" g
WHERE p.NAME = 'ERP系统升级' AND g.NAME = '测试组'
AND NOT EXISTS (
    SELECT 1 FROM ZRLDATABASE.PROJECT_MEMBERS pm 
    WHERE pm.MEMBER_NAME = '王五' AND pm.PROJECT_ID = p.ID
);

-- 为安全防护体系项目添加成员
INSERT INTO ZRLDATABASE.PROJECT_MEMBERS (PROJECT_ID, GROUP_ID, MEMBER_NAME, POSITION, MEMBER_STATUS)
SELECT 
    p.ID AS PROJECT_ID,
    g.ID AS GROUP_ID,
    '赵六' AS MEMBER_NAME,
    '安全工程师' AS POSITION,
    1 AS MEMBER_STATUS
FROM ZRLDATABASE.PROJECTS p, ZRLDATABASE."GROUPS" g
WHERE p.NAME = '安全防护体系' AND g.NAME = '开发组'
AND NOT EXISTS (
    SELECT 1 FROM ZRLDATABASE.PROJECT_MEMBERS pm 
    WHERE pm.MEMBER_NAME = '赵六' AND pm.PROJECT_ID = p.ID
);

-- 提交事务
COMMIT;

-- 4. 显示最终的统计数据
SELECT '====== 初始化完成 ======' AS "信息" FROM DUAL;

SELECT 
    '项目表' AS "表名", 
    COUNT(*) AS "记录数" 
FROM ZRLDATABASE.PROJECTS
UNION ALL
SELECT 
    '分组表', 
    COUNT(*) 
FROM ZRLDATABASE."GROUPS"
UNION ALL
SELECT 
    '项目成员表', 
    COUNT(*) 
FROM ZRLDATABASE.PROJECT_MEMBERS;

-- 5. 显示详细数据
SELECT '====== 分组表数据 ======' AS "信息" FROM DUAL;
SELECT ID, NAME FROM ZRLDATABASE."GROUPS" ORDER BY ID;

SELECT '====== 项目表数据 ======' AS "信息" FROM DUAL;
SELECT ID, NAME, DESCRIPTION, 
       CASE STATUS 
           WHEN 1 THEN '待分配'
           WHEN 2 THEN '进行中'
           WHEN 3 THEN '已完成'
           ELSE '未知'
       END AS 状态,
       CREATE_TIME
FROM ZRLDATABASE.PROJECTS ORDER BY ID;

SELECT '====== 项目成员表数据 ======' AS "信息" FROM DUAL;
SELECT 
    pm.ID,
    p.NAME AS "项目名",
    g.NAME AS "分组名",
    pm.MEMBER_NAME AS "成员姓名",
    pm.POSITION AS "职位",
    CASE pm.MEMBER_STATUS 
        WHEN 1 THEN '待分配'
        WHEN 2 THEN '进行中'
        WHEN 3 THEN '已完成'
        ELSE '未知'
    END AS "状态"
FROM ZRLDATABASE.PROJECT_MEMBERS pm
LEFT JOIN ZRLDATABASE.PROJECTS p ON pm.PROJECT_ID = p.ID
LEFT JOIN ZRLDATABASE."GROUPS" g ON pm.GROUP_ID = g.ID
ORDER BY p.ID, g.NAME, pm.ID;