-- 1. 项目表
CREATE TABLE PROJECTS (
    ID INT PRIMARY KEY IDENTITY,
    NAME NVARCHAR(100) NOT NULL,          -- 项目名
    DESCRIPTION NVARCHAR(500) NULL,       -- 项目描述
    STATUS INT DEFAULT 1 NOT NULL,        -- 项目状态：1.待分配 2.进行中 3.已完成
    CREATE_TIME DATETIME DEFAULT NOW()
);

-- 2. 人员分组表
CREATE TABLE "GROUPS" (
    ID INT PRIMARY KEY IDENTITY,
    NAME NVARCHAR(50) NOT NULL UNIQUE
);

-- 3. 项目成员表（核心关联表，记录人员属于哪个分组、参与了哪个项目及状态）
CREATE TABLE PROJECT_MEMBERS (
    ID INT PRIMARY KEY IDENTITY,
    PROJECT_ID INT NOT NULL,
    GROUP_ID INT NULL,                    -- 注意：此处字段名也无需引号，直接写 GROUP_ID 即可
    MEMBER_NAME NVARCHAR(50) NOT NULL,
    POSITION NVARCHAR(50) NULL,
    MEMBER_STATUS INT DEFAULT 1 NOT NULL,
    FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(ID),
    FOREIGN KEY (GROUP_ID) REFERENCES "GROUPS"(ID) -- 只对表名 "GROUPS" 使用双引号
);