-- 验证数据完整性
SELECT 
    '项目表' AS 表名, COUNT(*) AS 记录数 FROM ZRLDATABASE.PROJECTS
UNION ALL
SELECT '分组表', COUNT(*) FROM ZRLDATABASE."GROUPS"
UNION ALL
SELECT '项目成员表', COUNT(*) FROM ZRLDATABASE.PROJECT_MEMBERS;

-- 查看外键关系
SELECT 
    p.NAME AS 项目名,
    COUNT(pm.ID) AS 成员数,
    g.NAME AS 分组名,
    pm.MEMBER_NAME AS 成员姓名,
    pm.POSITION AS 职位
FROM ZRLDATABASE.PROJECTS p
LEFT JOIN ZRLDATABASE.PROJECT_MEMBERS pm ON p.ID = pm.PROJECT_ID
LEFT JOIN ZRLDATABASE."GROUPS" g ON pm.GROUP_ID = g.ID
GROUP BY p.NAME, g.NAME, pm.MEMBER_NAME, pm.POSITION
ORDER BY p.NAME, g.NAME;

-- 检查无效的外键引用
SELECT 
    pm.ID AS 成员ID,
    pm.MEMBER_NAME AS 成员姓名,
    pm.GROUP_ID AS 分组ID,
    CASE 
        WHEN g.ID IS NULL THEN '无效分组引用'
        ELSE '有效'
    END AS 状态
FROM ZRLDATABASE.PROJECT_MEMBERS pm
LEFT JOIN ZRLDATABASE."GROUPS" g ON pm.GROUP_ID = g.ID
WHERE g.ID IS NULL AND pm.GROUP_ID IS NOT NULL;